# Generated by Django 4.2 on 2024-04-08 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_studing', '0004_course_price'),
        ('users', '0003_payment_payment_id_payment_payment_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сurrent_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id сессии оплаты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_studing.course', verbose_name='курс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Текущая оплата курса',
                'verbose_name_plural': 'Текущие оплаты курса',
            },
        ),
    ]
