# Generated by Django 4.2 on 2024-04-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_сurrent_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
